---
  Package:
    packagedElements:
      - Package:
          id: 3l8cYkYl_KVsMsQtR5ax2IE76CsM
          profileApplications:
            - ProfileApplication:
                appliedProfile: ZjvD1bCxVklVQI7SsmtE_kS3oIIc
      - Profile:
          id: ZjvD1bCxVklVQI7SsmtE_kS3oIIc
...
