name: CMake

on:
  push:
    branches: [ master , develop ]
  pull_request:
    branches: [ master, develop ]

env:
  BUILD_TYPE: Release
  CC: /usr/bin/clang
  CXX: /usr/bin/clang++

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install build dependencies
      run: sudo apt-get install -y clang googletest libyaml-cpp-dev
    
    - uses: actions/checkout@v2
    - name: "create and enter build dir"
      run: mkdir build; cd build

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -j

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ${{github.workspace}}/build/umltest
