name: CMake

on:
  push:
    branches: [ master , develop ]
  pull_request:
    branches: [ master, develop ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install build dependencies
      run: sudo apt-get install -y build-essential libgtest-dev libgmock-dev libyaml-cpp-dev
  
    - name: "create and enter build dir"
      uses: actions/checkout@v2

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: mkdir build; cd build; cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ${{github.workspace}}/build/umltest
